import Head from "next/head";
import { GetStaticProps } from 'next';

import { getCourses } from "../../../../lib/getCourses";
import { getLessons, LessonFileContent } from "../../../../lib/getLessons";
import { getLesson } from "../../../../lib/getLesson";

interface Lesson {
    course_id: string
    lessonFileContent: LessonFileContent
}

export default function Lesson(props: Lesson) {

    return <>
        <Head>
            <title>{props?.course_id} - {props?.lessonFileContent.lesson_id}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    </>
}


export const getStaticProps: GetStaticProps = async (context) => {

    const course_id = context.params?.course as string;
    const lesson_id = context.params?.lesson as string;

    const lessonFileContent = getLesson('en', course_id, lesson_id);

    return {
        props: {
            course_id,
            lessonFileContent
        },
    };
}

export const getStaticPaths = async () => {

    const courses = getCourses('en');

    interface Path {
        params: { course: string; lesson: string; }
    }

    const paths: Path[] = [];
  
    courses.forEach((course) => {
    
        getLessons('en', course.course_id).forEach((lesson) => {

            return paths.push({ params: { course: course.course_id, lesson: lesson.lesson_id } });

        })

    })
  
    return { paths, fallback: false }
}