import Head from "next/head";
import { GetStaticProps } from 'next';

import Grid from "@mui/material/Grid";

interface Editor {

}

export default function Editor(props: Editor) {

    return <>
        <Head>
            <title>Editor</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Grid container spacing={4} columns={{ xs: 4, md: 12 }}>
            <Grid item xs={4} md={4}>
                Editor
            </Grid>
            <Grid item xs={4} md={4}>
                Preview
            </Grid>
        </Grid>
    </>
}

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            
        },
    };
}