import Head from "next/head";

import Grid from "@mui/material/Grid";

import GeneralContainer from "../../components/ui/generalContainer/generalContainer";
import PageIntro from "../../components/ui/pageIntro/pageIntro";

export default function Courses(props: any) {

    return <>
        <Head>
            <title>Courses</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <GeneralContainer>
            <PageIntro
                title="Courses"
                image='https://www.kaggle.com/static/images/education/km/learn-home-208h.png'
            >
                <p>Choose from an array of premium to free courses.</p>
                <p>We have free courses to support you to agnostic to whether or not you have bought a premium course.</p>
            </PageIntro>
        </GeneralContainer>
        <GeneralContainer>
            <Grid container spacing={4} columns={{ xs: 4, md: 12 }}>
                {/* {
                    props.courses.map(course => {
                        return <Grid item key={course.title} xs={4} md={4}>
                            <CourseCard title={course.title} board={course.board} link={`/courses/${course.id}`} />
                        </Grid>
                    })
                } */}
            </Grid>
        </GeneralContainer>
    </>
}

// export async function getStaticProps() {

//     // const courses = getCoursesMetaData();

//     return {
//         props: {
//             courses,
//         },
//     };
// }