import Head from "next/head";

import Grid from "@mui/material/Grid";

import GeneralContainer from "../../components/ui/generalContainer/generalContainer";
import PageIntro from "../../components/ui/pageIntro/pageIntro";
import CourseCard from "../../components/ui/courseCard/courseCard";

import { getCourses, CourseFileContent } from "../../lib/getCourses";

interface Courses {
    courseFileContents: CourseFileContent[]
}

export default function Courses(props: Courses) {

    return <>
        <Head>
            <title>Courses</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <GeneralContainer>
            <PageIntro
                title="Courses"
                image='/assets/graph.svg'
            >
                <p>Start from the beginning or choose where to start!</p>
                <p>MathOnTrack teaches you the fundamentals of Mathematics and beyond.</p>
            </PageIntro>
        </GeneralContainer>
        <GeneralContainer>
            <Grid container spacing={4} columns={{ xs: 4, md: 12 }}>
                {
                    props.courseFileContents.map(courseFileContent => {
                        return (
                            <Grid item key={courseFileContent.course_id} xs={4} md={4}>
                                <CourseCard
                                    title={courseFileContent.course_title} 
                                    description={courseFileContent.course_description} 
                                    link={`/learn/${courseFileContent.course_id}/lessons`} 
                                />
                            </Grid>
                        )
                    })
                }
            </Grid>
        </GeneralContainer>
    </>
}

export async function getStaticProps() {

    const courseFileContents = getCourses('en');

    return {
        props: {
            courseFileContents
        },
    };
}