import Head from 'next/head';
import Box from "@mui/material/Box";
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';

import GeneralContainer from '../components/ui/generalContainer/generalContainer';

// Next Imports
import Link from 'next/link';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>MathOnTrack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GeneralContainer>
        <Typography variant="h3" component="div" gutterBottom>
          Learn Mathematics - For free.
        </Typography>
        <Typography variant="h3" component="div" gutterBottom>
          Do exercises.
        </Typography>
        <Typography variant="h2" component="div" gutterBottom>
          Be more confident!
        </Typography>
        <Typography variant="h3" component="div" gutterBottom>
          At your job, in your school or your university.
        </Typography>
      </GeneralContainer>
      <GeneralContainer>
        <Link href={"/learn"}>
          <Button variant='contained' sx={{ width: "100%", height: 100, fontSize: 24 }}>
            Get Started, it is always for free!
          </Button>
        </Link>
      </GeneralContainer>
      <Box 
          component={'img'}
          src={ 'assets/background.png' }
          sx={{ width: '100%' }}
        />
    </Box>
  )
}
