import Head from 'next/head';
import Box from "@mui/material/Box";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>MathOnTrack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Box>
  )
}
